export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGNED_IN = 'AUTH_SIGNED_IN';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
export const AUTH_STATE_CHANGED = 'AUTH_STATE_CHANGED';
export const AUTH_GET_CURRENT = 'AUTH_GET_CURRENT';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_INITIALIZED = 'AUTH_INITIALIZED';

export const SESSIONS_ADD_USER = 'SESSIONS_ADD_USER';
export const SESSIONS_ADD_SESSION = 'SESSIONS_ADD_SESSION';
export const SESSIONS_GET_SESSIONS = 'SESSIONS_GET_SESSIONS';
export const SESSIONS_SESSIONS_FETCHED = 'SESSIONS_SESSIONS_FETCHED';
export const SESSIONS_SESSION_ADDED = 'SESSIONS_SESSION_ADDED';
export const SESSIONS_REMOVE_SESSION = 'SESSIONS_REMOVE_SESSION';
export const SESSIONS_SESSION_REMOVED = 'SESSIONS_SESSION_REMOVED';
export const SESSIONS_JOIN_SESSION = 'SESSIONS_JOIN_SESSION';
export const SESSIONS_JOINED_SESSION = 'SESSIONS_JOINED_SESSION';
export const SESSIONS_LEAVE_SESSION = 'SESSIONS_LEAVE_SESSION';

export const UI_LOADING_STARTED = 'UI_LOADING_STARTED';
export const UI_LOADING_FINISHED = 'UI_LOADING_FINISHED';

export const IO_CONNECT = 'IO_CONNECT';
export const IO_CONNECTED = 'IO_CONNECTED';
