export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGNED_IN = 'AUTH_SIGNED_IN';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
export const AUTH_STATE_CHANGED = 'AUTH_STATE_CHANGED';
export const AUTH_GET_CURRENT = 'AUTH_GET_CURRENT';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_INITIALIZED = 'AUTH_INITIALIZED';

export const DB_ADD_USER = 'DB_ADD_USER';
export const DB_SET_USER_PATH = 'DB_SET_USER_PATH';
export const DB_ADD_SESSION = 'DB_ADD_SESSION';
export const DB_GET_SESSIONS = 'DB_GET_SESSIONS';
export const DB_SESSIONS_FETCHED = 'DB_SESSIONS_FETCHED';
export const DB_SESSION_ADDED = 'DB_SESSION_ADDED';
export const DB_SESSION_REMOVED = 'DB_SESSION_REMOVED';
